defaults:
  - _self_
  - agent: encirl
  - suite: atari
  - override hydra/launcher: submitit_local

# Root Dir
root_dir: '/home/ubuntu/duxinghao/crs/PatchAIL'

# replay buffer
replay_buffer_size: 1000000 # 150000
replay_buffer_num_workers: 1
initial_buffer_num_workers: 1
nstep: 3
batch_size: 256 # 128
# misc
seed: 2
device: cuda
save_video: true
save_train_video: false
use_tb: true
algo_name: 'encirl'
record_video: false

# experiment
obs_type: 'pixels' # pixels, features
reward_type: 'airl' # airl, gail, gail2
experiment: eta=${agent.eta}&mix_td=${agent.mix_td}&argmax/seed=${seed}

# expert dataset
num_demos: 20 #50(openaigym), 10(dmc), 1(metaworld), 1(particle), 1(robotgym)
expert_dataset: '${root_dir}/PatchAIL/expert_demos/${suite.name}/${task_name}/expert_demos.pkl'

hydra:
  run:
    dir: ./exp_local/${suite.name}_${task_name}_${obs_type}/${experiment}/${now:%Y.%m.%d}/${now:%H%M%S}
  sweep:
    dir: ./exp_local/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    tasks_per_node: 1
    nodes: 1
    submitit_folder: ./exp/${suite.name}_${task_name}/${now:%H%M%S}_${experiment}/.slurm
